#!/usr/bin/env python3
from __future__ import annotations
import csv
from pathlib import Path

OUT = Path(__file__).resolve().parents[1]


def wcsv(name, fieldnames, rows):
    path = OUT / name
    with path.open("w", newline="", encoding="utf-8") as f:
        wr = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        wr.writeheader()
        for r in rows:
            for k in fieldnames:
                r.setdefault(k, "")
            wr.writerow(r)
    parsed = list(csv.DictReader(path.open(encoding="utf-8")))
    assert parsed and all(len(r) == len(fieldnames) for r in parsed), name
    print(name, len(parsed))


# ---- SPARSITY / BIAS ----
BCOLS = ["Issue", "Description", "How to detect", "How to measure impact", "Mitigation options",
         "Situations where mitigation fails", "Implications for FishAI", "Evidence strength", "sources"]
bias = []


def b(issue, desc, det, meas, mit, fail, impl, ev="STRONG_REPLICATED", src="S80; P010"):
    bias.append(dict(Issue=issue, Description=desc, **{"How to detect": det, "How to measure impact": meas,
               "Mitigation options": mit, "Situations where mitigation fails": fail,
               "Implications for FishAI": impl, "Evidence strength": ev, "sources": src}))


b("sparse observations", "Few events relative to the map asked for",
  "Event counts per year/stratum; empty cells",
  "Width of cluster-bootstrap intervals; events-per-variable",
  "Coarser grain; fewer covariates; do not map empty ocean",
  "Fine nowcast grids still look precise",
  "SBC has 11 sites; FGB n=38 in 2024", "STRONG_REPLICATED", "P005")
b("rare species", "Few detections so always-absent wins accuracy",
  "Training detections <50 or test <10",
  "Prevalence; Brier of constant-zero vs model",
  "Do not model; withhold sensitive sites",
  "People still want maps of rare valuable fish",
  "Goliath 8 Keys events; barred sand bass 9 usable 2022 detections", "STRONG_REPLICATED", "HARSH_PRODUCT_AUDIT.md")
b("zero inflation", "Many true or protocol zeros plus clumping",
  "Histogram of counts; extra zeros vs binomial",
  "Hurdle vs binomial Brier on later year",
  "Hurdle/delta; do not invent zeros",
  "Zeros from missing species lists",
  "RVC detection is already binary after collapse; counts still zero-inflated", "MODERATE", "S72")
b("false zeros", "Species present but not recorded, or list incomplete",
  "Coverage of species on year list; -99999; missing vis",
  "Compare years with vs without the code",
  "NOT_EVALUATED never zero; refuse missing covariates",
  "Pacific NCRMP COUNT files have no zeros to recover",
  "Core FishAI constructor; Pacific remains presence-only", "STRONG_REPLICATED", "S42; ZERO_SEMANTICS_AUDIT.md")
b("false positives", "Mis-ID, eDNA contamination, compiler errors",
  "Expert review; lab controls; impossible ranges",
  "Occupancy models with false-positive parameters if repeats exist",
  "Controls; withhold; do not treat compiler pins as surveys",
  "Single eDNA hit",
  "RVC ID error unknown; eDNA not in holdings", "MODERATE", "S37")
b("detection bias", "p varies with visibility, observer, complexity, size",
  "Fit p covariates; residual vs vis",
  "Change in Brier when vis included (Keys kept vis)",
  "Keep vis as observation covariate not habitat",
  "No vis field (SBC missing vis dropped a row)",
  "Do not call vis a preference for clear water", "STRONG_REPLICATED", "S42")
b("effort variation", "Unequal search time/area",
  "Effort fields missing or varying",
  "CPUE vs raw catch; offset models",
  "Standardize to one protocol; require effort",
  "Citizen pins have no effort",
  "RVC and SBC effort is the protocol itself", "STRONG_REPLICATED", "S80")
b("uneven geographic coverage", "Some habitats never sampled",
  "Map of effort vs habitat raster",
  "Extrapolation flags; AOA",
  "Support mask; refuse unsampled habitat",
  "Users want a coast-wide fill",
  "Predictions only on surveyed habitat classes", "STRONG_REPLICATED", "P008")
b("repeated popular sites", "Same sites dominate (SBC fixed; citizen hotspots)",
  "Site frequency table",
  "Cluster bootstrap by site; site-out CV",
  "Cluster SEs; do not treat revisits as new places",
  "11 sites: CV is coarse",
  "SBC bootstrap over 11 sites; Keys PSU clustering", "STRONG_REPLICATED", "P005")
b("accessible-site bias", "Samples near ramps, cities, calm days",
  "Distance-to-access vs detections",
  "Compare designed survey vs opportunistic",
  "Prefer probability samples; bias layers for compilers",
  "Cannot recover unsampled wilderness from pins",
  "RVC is stratified random; GBIF is not", "STRONG_REPLICATED", "S67; S80")
b("depth bias", "Surveys miss fish outside the band; surface env used for bottom fish",
  "Depth range of gear vs species; SST vs bottom T",
  "Skill of surface vs depth-resolved T (Keys: depth T did not help)",
  "Join at occupied depth; do not use SST as bottom proxy without evidence",
  "No per-transect depth (SBC)",
  "HYCOM at dive depth was the right test; still failed as kept feature", "MODERATE", "BEHAVIOR_VARIABLE_CATALOG.csv")
b("seasonal bias", "Only summer surveys",
  "Month histogram",
  "Cannot validate winter claims",
  "Restrict card to survey months; refuse other seasons",
  "Dynamic habitat products still draw winter maps",
  "SBC late Jul-Aug only; RVC mostly summer", "STRONG_REPLICATED", "CORE_PROBLEM_DEFINITION.md")
b("gear bias", "Trawl vs diver vs camera catch different sizes/habitats",
  "Overlapping surveys disagree",
  "Catchability ratios; hold out a gear",
  "Separate likelihoods; never pool y",
  "One 'presence' column",
  "Do not mix RVC and DATRAS zeros", "STRONG_REPLICATED", "S69; S70")
b("observer bias", "Skill and behavior differ among divers",
  "Observer IDs if recorded; residual clustering",
  "Variance components",
  "Observer random effects if IDs exist",
  "IDs absent in current fits",
  "Not in current Keys model", "MODERATE", "S80")
b("changing taxonomy", "Splits/synonyms split a series",
  "Code vs accepted-name map missing (TAX-001)",
  "Sudden prevalence jumps at list changes",
  "WoRMS map; do not invent AphiaIDs",
  "Unpublished synonymy",
  "Codes used raw", "MODERATE", "TAXONOMY_SEMANTIC_ERRORS.csv")
b("changing survey protocols", "Cylinder radius, time, or list changes",
  "Protocol metadata by year",
  "Breaks in mean NUM",
  "Segment models; do not pool silently",
  "Undocumented changes",
  "RVC list size changes by year; zeros only if code on list", "STRONG_REPLICATED", "ZERO_SEMANTICS_AUDIT.md")
b("missing environmental grids", "Coastal cells NaN; chlorophyll masked",
  "Valid-fraction maps; join-failure counts",
  "Dropped rows; Keys HYCOM ~51% ocean cells at 0-30 m",
  "Nearest valid ocean cell with km cap; refuse if none",
  "VIIRS all-NaN over reef",
  "Documented in Keys env QA; chl not used", "MODERATE", "FISHAI_DATA_GAP_ANALYSIS.md")
b("coastal interpolation errors", "Land bleed; wrong shoreline",
  "Land mask checks; barrier mesh",
  "Impossible values on land",
  "Barrier SPDE; land mask",
  "Coarse 1/12 deg still smears inshore",
  "Required if spatial models are fit", "MODERATE", "S73")
b("correlated predictors", "SST, season, and depth travel together",
  "VIF; pairwise corr",
  "Unstable coefficients; CV vs later-year disagreement",
  "Drop redundant; pre-register one thermal metric",
  "Warm years = high detections (kelp bass)",
  "Temperature kept in SBC CV then failed 2022", "STRONG_REPLICATED", "P009")
b("spatial autocorrelation", "Nearby dives not independent",
  "Residual variogram; Moran's I",
  "Too-narrow CIs if ignored (P010)",
  "Cluster bootstrap; spatial GLMM",
  "11 sites cannot identify a field",
  "Already cluster by PSU/site", "STRONG_REPLICATED", "P010")
b("temporal autocorrelation", "Years are few and dependent",
  "ACF of yearly prevalence",
  "Random year split overstates skill",
  "Later-year holdout only",
  "One leftover year after burning 2022/2023",
  "PR 2023 and SBC/Keys 2022 burned for tested species", "STRONG_REPLICATED", "P005")
b("species aggregation", "Schools make extra zeros and extra highs",
  "Variance >> mean",
  "Poor Poisson fit",
  "Hurdle; do not claim abundance from detection",
  "Schooling pelagics on reef surveys",
  "Detection still OK for common site-attached reef fish", "MODERATE", "S72")
b("movement between repeated surveys", "Closure fails",
  "Tag evidence; occupancy GOF",
  "psi/p not identifiable",
  "Shorter windows; do not use N-mixture on RVC",
  "Annual revisits are not closed",
  "Occupancy not supported on current design", "STRONG_REPLICATED", "S43; S42")
b("range-edge extrapolation", "Predict beyond observed envelope",
  "MESS/ExDet/AOA; min-max checks",
  "Skill drop in novel cells",
  "Refuse out-of-range; mask",
  "Smooths still extrapolate",
  "predict() refuses; score() still scored 5 cold SBC rows", "MODERATE", "P007; P008")
b("climate novelty", "Test climate outside training",
  "Compare covariate distributions; heatwave flags (S83)",
  "Later-year failure after CV pass (P009; kelp bass)",
  "Do not keep env terms that fail later years; ensemble climate only for Q9",
  "No amount of SST skill in 2014-2018 guarantees 2022",
  "Treat heatwave and post-heatwave years as novelty", "STRONG_REPLICATED", "P009; P006; S83")
b("preferential sampling", "Effort follows expected catch",
  "Effort map vs habitat; fishery vs survey mismatch",
  "Inflated suitability in fished cells",
  "Designed surveys; joint sampling models; never AIS-as-fish",
  "Citizen apps",
  "Safety: no catch hotspots", "STRONG_REPLICATED", "S67; S80")
b("data leakage", "Future covariates, holdout reuse, multiple estimators as one",
  "Offset signs; train-year list; RESULTS_LOCKED",
  "Inflated Brier (PR 2023 untrusted)",
  "Causal offsets {0,-1,-2}; freeze; one estimator; locks",
  "Exploration already printed 2022 counts (SBC disclosed)",
  "Guards exist; do not rescore burned years", "STRONG_REPLICATED", "brutal-audit EXECUTION_REPORT.md")
b("covariate shift", "Test year env or prevalence differs",
  "Train vs test histograms; calibration gap",
  "Keys gap 0.053; kelp bass 0.38 vs 0.60",
  "Survey-only model; drop shifted covariate",
  "Confounded year effects",
  "Main remaining failure mode for 'working' models", "STRONG_REPLICATED", "VALIDATION_AND_BACKTESTING_PROTOCOL.md")
b("small number of sites", "Spatial CV and bootstrap underpowered",
  "Unique sites << covariates",
  "CI includes 0 even when ranking looks OK",
  "Do not fit spatial fields; do not claim nowcast",
  "More years at the same 11 sites still 11 places",
  "SBC models failed; Channel Islands would be a new frame", "STRONG_REPLICATED", "socal SUMMARY.md")

wcsv("SPARSE_DATA_AND_BIAS_MATRIX.csv", BCOLS, bias)

# ---- OBSERVATION METHODS (compact) ----
OCOLS = ["Observation method", "What is recorded", "Unit of observation", "Effort measure",
         "Explicit zeros available?", "Repeated visits?", "Detection modifiers", "False-negative sources",
         "False-positive sources", "Size or life-stage selectivity", "Spatial footprint", "Temporal resolution",
         "Typical data latency", "Public availability", "Questions supported (of the nine)",
         "Questions not supported", "FishAI holdings", "sources"]


def o(**k):
    return k


obs = [
    o(**{"Observation method": "RVC stationary point count", "What is recorded": "NUM average per length bin in a cylinder",
        "Unit of observation": "dive / point count", "Effort measure": "fixed protocol (~10 min, 7.5 m radius typical)",
        "Explicit zeros available?": "yes if species on year list", "Repeated visits?": "no (design)",
        "Detection modifiers": "vis, depth, habitat complexity, observer", "False-negative sources": "cryptic, poor vis, outside cylinder",
        "False-positive sources": "mis-ID", "Size or life-stage selectivity": "length bins; small/cryptic missed",
        "Spatial footprint": "tens of m", "Temporal resolution": "minutes; survey every 1-2 years",
        "Typical data latency": "1-2 years to public ERDDAP", "Public availability": "NOAA NCEI ERDDAP",
        "Questions supported (of the nine)": "2; 3 as index; weakly 1", "Questions not supported": "4,6-8; occupancy",
        "FishAI holdings": "Keys 2014-24 (no 2021 Keys dives); PR; USVI; FGB", "sources": "S41"}),
    o(**{"Observation method": "Belt-transect UVC (SBC/PISCO)", "What is recorded": "counts by size on a strip",
        "Unit of observation": "transect x date", "Effort measure": "area (SBC 40x2 m)",
        "Explicit zeros available?": "yes (SBC); -99999 missing", "Repeated visits?": "annual same sites",
        "Detection modifiers": "kelp, vis, swell, observer", "False-negative sources": "cryptic protocol excluded if not used",
        "False-positive sources": "mis-ID", "Size or life-stage selectivity": "size bins",
        "Spatial footprint": "80 m2", "Temporal resolution": "annual Jul-Aug",
        "Typical data latency": "months-year (EDI/DataONE)", "Public availability": "SBC LTER CC BY 4.0",
        "Questions supported (of the nine)": "2,3; 5 only as year-to-year at 11 sites", "Questions not supported": "4,7-8 winter",
        "FishAI holdings": "knb-lter-sbc.17.41 and kelp 18.30", "sources": "socal SUMMARY.md"}),
    o(**{"Observation method": "REEF roving diver", "What is recorded": "abundance categories on a swim",
        "Unit of observation": "survey", "Effort measure": "time; not a complete list always",
        "Explicit zeros available?": "no (unseen taxa omitted)", "Repeated visits?": "opportunistic",
        "Detection modifiers": "diver skill, site choice", "False-negative sources": "non-reporting",
        "False-positive sources": "mis-ID", "Size or life-stage selectivity": "conspicuous fish",
        "Spatial footprint": "dive site", "Temporal resolution": "irregular",
        "Typical data latency": "variable", "Public availability": "some summaries",
        "Questions supported (of the nine)": "relative 1 only", "Questions not supported": "2-9",
        "FishAI holdings": "none as training", "sources": "S80"}),
    o(**{"Observation method": "Stereo diver-operated video", "What is recorded": "counts/lengths in FOV",
        "Unit of observation": "transect/video", "Effort measure": "area/time",
        "Explicit zeros available?": "if complete review", "Repeated visits?": "design-dependent",
        "Detection modifiers": "visibility, annotation", "False-negative sources": "cryptic, poor video",
        "False-positive sources": "ID error", "Size or life-stage selectivity": "measurable lengths",
        "Spatial footprint": "transect", "Temporal resolution": "survey",
        "Typical data latency": "months", "Public availability": "program-specific",
        "Questions supported (of the nine)": "2,3", "Questions not supported": "4,7",
        "FishAI holdings": "none", "sources": "SENSOR_NETWORK_MATRIX.csv"}),
    o(**{"Observation method": "BRUV", "What is recorded": "MaxN, lengths",
        "Unit of observation": "soak", "Effort measure": "soak time; bait plume unknown",
        "Explicit zeros available?": "yes if reviewed", "Repeated visits?": "design-dependent",
        "Detection modifiers": "bait, vis, currents", "False-negative sources": "no attraction; FOV",
        "False-positive sources": "ID", "Size or life-stage selectivity": "attracted species",
        "Spatial footprint": "unknown effective area", "Temporal resolution": "hours",
        "Typical data latency": "months", "Public availability": "some programs (G-FISHER)",
        "Questions supported (of the nine)": "3 relative", "Questions not supported": "absolute N; 4",
        "FishAI holdings": "none", "sources": "SENSOR_NETWORK_MATRIX.csv"}),
    o(**{"Observation method": "Unbaited camera / ROV / towed video", "What is recorded": "counts in FOV",
        "Unit of observation": "segment", "Effort measure": "area/time",
        "Explicit zeros available?": "if complete", "Repeated visits?": "design-dependent",
        "Detection modifiers": "altitude, lights, vis", "False-negative sources": "avoidance, FOV",
        "False-positive sources": "ID", "Size or life-stage selectivity": "visible sizes",
        "Spatial footprint": "transect", "Temporal resolution": "survey",
        "Typical data latency": "months", "Public availability": "variable",
        "Questions supported (of the nine)": "2,3", "Questions not supported": "4,7",
        "FishAI holdings": "none", "sources": "SENSOR_NETWORK_MATRIX.csv"}),
    o(**{"Observation method": "Bottom trawl survey", "What is recorded": "catch by species/size",
        "Unit of observation": "haul", "Effort measure": "duration, distance, swept area",
        "Explicit zeros available?": "on completed hauls if full list", "Repeated visits?": "stations by year",
        "Detection modifiers": "gear, bottom type, time of day", "False-negative sources": "untrawlable, herding, mesh",
        "False-positive sources": "rare", "Size or life-stage selectivity": "mesh and gear",
        "Spatial footprint": "km of tow", "Temporal resolution": "seasonal surveys",
        "Typical data latency": "months-year", "Public availability": "DATRAS, DFO, NOAA (program-specific)",
        "Questions supported (of the nine)": "1,3,5", "Questions not supported": "4, reef untrawlable",
        "FishAI holdings": "NS-IBTS 2019 Q1; DFO 2023 sample", "sources": "S72"}),
    o(**{"Observation method": "Midwater trawl", "What is recorded": "pelagic catch",
        "Unit of observation": "haul", "Effort measure": "duration/volume",
        "Explicit zeros available?": "if recorded", "Repeated visits?": "survey design",
        "Detection modifiers": "depth of gear vs DVM", "False-negative sources": "avoidance, depth mismatch",
        "False-positive sources": "rare", "Size or life-stage selectivity": "mesh",
        "Spatial footprint": "tow", "Temporal resolution": "survey",
        "Typical data latency": "months", "Public availability": "some CPS surveys",
        "Questions supported (of the nine)": "3", "Questions not supported": "2 reef",
        "FishAI holdings": "none (FRD CPS discovered, not downloaded)", "sources": "discovery-candidates.csv"}),
    o(**{"Observation method": "Longline survey", "What is recorded": "catch per hook",
        "Unit of observation": "set", "Effort measure": "hooks x soak",
        "Explicit zeros available?": "if all hooks recorded", "Repeated visits?": "design",
        "Detection modifiers": "bait, soak, depth", "False-negative sources": "satiation, depredation",
        "False-positive sources": "rare", "Size or life-stage selectivity": "hook size",
        "Spatial footprint": "km of line", "Temporal resolution": "survey",
        "Typical data latency": "months", "Public availability": "some NMFS",
        "Questions supported (of the nine)": "3", "Questions not supported": "2,4",
        "FishAI holdings": "none", "sources": "S75"}),
    o(**{"Observation method": "Seine / beach seine", "What is recorded": "catch in net",
        "Unit of observation": "haul", "Effort measure": "area/hauls",
        "Explicit zeros available?": "if recorded", "Repeated visits?": "design",
        "Detection modifiers": "habitat, tide", "False-negative sources": "escape",
        "False-positive sources": "rare", "Size or life-stage selectivity": "mesh; juveniles often",
        "Spatial footprint": "local", "Temporal resolution": "survey",
        "Typical data latency": "months", "Public availability": "variable",
        "Questions supported (of the nine)": "3 juveniles", "Questions not supported": "adult reef",
        "FishAI holdings": "none", "sources": "ABUNDANCE_ESTIMATION_MATRIX.csv"}),
    o(**{"Observation method": "Gillnet", "What is recorded": "catch",
        "Unit of observation": "set", "Effort measure": "net-hours",
        "Explicit zeros available?": "if recorded", "Repeated visits?": "design",
        "Detection modifiers": "mesh, soak", "False-negative sources": "selectivity",
        "False-positive sources": "rare", "Size or life-stage selectivity": "strong",
        "Spatial footprint": "local", "Temporal resolution": "set",
        "Typical data latency": "variable", "Public availability": "often restricted",
        "Questions supported (of the nine)": "3 relative", "Questions not supported": "2",
        "FishAI holdings": "none", "sources": "S75"}),
    o(**{"Observation method": "Hook-and-line surveys", "What is recorded": "catch",
        "Unit of observation": "station/time", "Effort measure": "hook-hours",
        "Explicit zeros available?": "if zeros recorded", "Repeated visits?": "design",
        "Detection modifiers": "bait, skill", "False-negative sources": "not biting",
        "False-positive sources": "rare", "Size or life-stage selectivity": "gear",
        "Spatial footprint": "station", "Temporal resolution": "survey",
        "Typical data latency": "variable", "Public availability": "some",
        "Questions supported (of the nine)": "3", "Questions not supported": "4",
        "FishAI holdings": "none", "sources": "S75"}),
    o(**{"Observation method": "Fishery-dependent logbook CPUE", "What is recorded": "catch and some effort",
        "Unit of observation": "trip/set", "Effort measure": "declared effort",
        "Explicit zeros available?": "often no (only positive trips)",
        "Repeated visits?": "fleet",
        "Detection modifiers": "targeting", "False-negative sources": "unreported zeros",
        "False-positive sources": "misreport", "Size or life-stage selectivity": "market",
        "Spatial footprint": "fishing grounds", "Temporal resolution": "daily-trip",
        "Typical data latency": "confidential", "Public availability": "aggregates only (MSA 402b)",
        "Questions supported (of the nine)": "3 index if standardized", "Questions not supported": "unbiased 1,2,7",
        "FishAI holdings": "none; must not seek vessel-level", "sources": "SAFETY_AND_NON_TARGETING_BOUNDARIES.md"}),
    o(**{"Observation method": "Scientific observer programs", "What is recorded": "catch, bycatch, locations",
        "Unit of observation": "haul with observer", "Effort measure": "observed effort",
        "Explicit zeros available?": "for recorded taxa", "Repeated visits?": "fleet",
        "Detection modifiers": "observer coverage", "False-negative sources": "unobserved hauls",
        "False-positive sources": "rare", "Size or life-stage selectivity": "gear",
        "Spatial footprint": "fleet", "Temporal resolution": "trip",
        "Typical data latency": "restricted", "Public availability": "confidential",
        "Questions supported (of the nine)": "3; EcoCast used observer+tags (S74)", "Questions not supported": "public maps",
        "FishAI holdings": "none", "sources": "S74"}),
    o(**{"Observation method": "VMS/AIS fishing effort", "What is recorded": "vessel movement; inferred fishing",
        "Unit of observation": "ping", "Effort measure": "hours fishing (inferred)",
        "Explicit zeros available?": "no (not fish)", "Repeated visits?": "n/a",
        "Detection modifiers": "AIS gaps, dark vessels", "False-negative sources": "off transponders",
        "False-positive sources": "non-fishing classified as fishing", "Size or life-stage selectivity": "n/a",
        "Spatial footprint": "global", "Temporal resolution": "hours",
        "Typical data latency": "days (GFW)", "Public availability": "GFW research products",
        "Questions supported (of the nine)": "none as fish location; bias covariate only", "Questions not supported": "1-9 as ecology",
        "FishAI holdings": "none; AIS never as fish location", "sources": "S01; SAFETY"}),
    o(**{"Observation method": "Active acoustics / echosounder survey", "What is recorded": "backscatter",
        "Unit of observation": "interval", "Effort measure": "track nautical miles",
        "Explicit zeros available?": "low Sa as low biomass not species zero", "Repeated visits?": "survey",
        "Detection modifiers": "TS, depth, noise", "False-negative sources": "near surface/bottom dead zone",
        "False-positive sources": "species mix", "Size or life-stage selectivity": "TS overlaps",
        "Spatial footprint": "transect", "Temporal resolution": "survey to real-time on vessel",
        "Typical data latency": "months for processed", "Public availability": "some",
        "Questions supported (of the nine)": "3 biomass proxy", "Questions not supported": "species ID; 2 reef",
        "FishAI holdings": "none", "sources": "SENSOR_NETWORK_MATRIX.csv"}),
    o(**{"Observation method": "FAD echosounder buoys", "What is recorded": "acoustic biomass index at buoy",
        "Unit of observation": "buoy-day", "Effort measure": "instrument time",
        "Explicit zeros available?": "low index not species absence", "Repeated visits?": "continuous",
        "Detection modifiers": "species mix, range", "False-negative sources": "fish away from FAD",
        "False-positive sources": "non-target", "Size or life-stage selectivity": "associated tuna/etc",
        "Spatial footprint": "FAD aggregation", "Temporal resolution": "hours",
        "Typical data latency": "industry", "Public availability": "mostly proprietary",
        "Questions supported (of the nine)": "3 research index", "Questions not supported": "public targeting",
        "FishAI holdings": "none; do not adopt as product", "sources": "COMMERCIAL analysis"}),
    o(**{"Observation method": "Passive acoustic monitoring", "What is recorded": "calls",
        "Unit of observation": "detector-day", "Effort measure": "recording time x range",
        "Explicit zeros available?": "no call ≠ absence", "Repeated visits?": "continuous",
        "Detection modifiers": "noise, propagation", "False-negative sources": "silent animals, masking",
        "False-positive sources": "classifier errors (S31 reported 0% false detections for 3 whale spp in one system)",
        "Size or life-stage selectivity": "vocalizing animals",
        "Spatial footprint": "range-dependent km", "Temporal resolution": "minutes to real-time",
        "Typical data latency": "real-time to months", "Public availability": "some whale products",
        "Questions supported (of the nine)": "local presence", "Questions not supported": "abundance without range; 2 RVC",
        "FishAI holdings": "none", "sources": "S31; S32"}),
    o(**{"Observation method": "eDNA metabarcoding", "What is recorded": "taxa in water",
        "Unit of observation": "sample", "Effort measure": "volume, replicates",
        "Explicit zeros available?": "nondetect is not absence", "Repeated visits?": "if designed",
        "Detection modifiers": "primers, inhibition, transport", "False-negative sources": "degradation, primers",
        "False-positive sources": "contamination, wastewater, advection (S37)",
        "Size or life-stage selectivity": "unknown mixed DNA",
        "Spatial footprint": "uncertain plume", "Temporal resolution": "sample time",
        "Typical data latency": "weeks-months", "Public availability": "growing",
        "Questions supported (of the nine)": "1 occupancy research", "Questions not supported": "2 RVC; abundance; 4",
        "FishAI holdings": "none", "sources": "S37"}),
    o(**{"Observation method": "eDNA qPCR/ddPCR", "What is recorded": "target copies",
        "Unit of observation": "sample", "Effort measure": "volume, replicates",
        "Explicit zeros available?": "nondetect ≠ absence", "Repeated visits?": "if designed",
        "Detection modifiers": "assay, inhibition", "False-negative sources": "LOD",
        "False-positive sources": "contamination", "Size or life-stage selectivity": "none",
        "Spatial footprint": "uncertain", "Temporal resolution": "sample",
        "Typical data latency": "weeks", "Public availability": "papers",
        "Questions supported (of the nine)": "local presence of one taxon", "Questions not supported": "3,4",
        "FishAI holdings": "none", "sources": "S37"}),
    o(**{"Observation method": "Acoustic telemetry", "What is recorded": "tag ID at receiver",
        "Unit of observation": "detection", "Effort measure": "receiver-days; range test",
        "Explicit zeros available?": "no ping ≠ away if out of range", "Repeated visits?": "continuous in array",
        "Detection modifiers": "range, noise, depth", "False-negative sources": "gaps, shedding",
        "False-positive sources": "code collisions (rare)", "Size or life-stage selectivity": "taggable animals",
        "Spatial footprint": "array", "Temporal resolution": "seconds-hours",
        "Typical data latency": "months (manual) to faster", "Public availability": "OTN/ATN by agreement",
        "Questions supported (of the nine)": "4", "Questions not supported": "1-3 population; 7 untagged",
        "FishAI holdings": "none", "sources": "S02; S11; S12"}),
    o(**{"Observation method": "Satellite telemetry", "What is recorded": "Doppler/GPS positions",
        "Unit of observation": "fix", "Effort measure": "duty cycle",
        "Explicit zeros available?": "n/a", "Repeated visits?": "track",
        "Detection modifiers": "surfacing, antenna", "False-negative sources": "no surface",
        "False-positive sources": "Argos error km", "Size or life-stage selectivity": "large animals",
        "Spatial footprint": "global", "Temporal resolution": "hours",
        "Typical data latency": "hours", "Public availability": "some Movebank",
        "Questions supported (of the nine)": "4", "Questions not supported": "untagged 1-3,7",
        "FishAI holdings": "none", "sources": "S02; S52"}),
    o(**{"Observation method": "Archival / PSAT tags", "What is recorded": "T, depth, light; pop-up summary",
        "Unit of observation": "track reconstruct", "Effort measure": "tag-days",
        "Explicit zeros available?": "n/a", "Repeated visits?": "n/a",
        "Detection modifiers": "geolocation error", "False-negative sources": "not recovered; no pop-up",
        "False-positive sources": "wrong geolocation", "Size or life-stage selectivity": "large",
        "Spatial footprint": "uncertain km-10s km", "Temporal resolution": "high internally",
        "Typical data latency": "months-years", "Public availability": "some",
        "Questions supported (of the nine)": "4", "Questions not supported": "7 live",
        "FishAI holdings": "none", "sources": "S02"}),
    o(**{"Observation method": "CalCOFI bongo nets", "What is recorded": "egg/larva counts",
        "Unit of observation": "tow", "Effort measure": "volume",
        "Explicit zeros available?": "per taxon if listed", "Repeated visits?": "station grid",
        "Detection modifiers": "time of day, depth", "False-negative sources": "patchiness, stage",
        "False-positive sources": "ID", "Size or life-stage selectivity": "eggs/larvae only",
        "Spatial footprint": "station", "Temporal resolution": "cruise",
        "Typical data latency": "year", "Public availability": "ERDDAP (some GET failed)",
        "Questions supported (of the nine)": "6 context; not adult 1-2", "Questions not supported": "adult 2,4,7",
        "FishAI holdings": "cruise 202204 sample", "sources": "FISHAI_DATA_GAP_ANALYSIS.md"}),
    o(**{"Observation method": "CUFES egg pump", "What is recorded": "eggs underway",
        "Unit of observation": "sample", "Effort measure": "volume/time",
        "Explicit zeros available?": "if recorded", "Repeated visits?": "along-track",
        "Detection modifiers": "pump depth", "False-negative sources": "eggs deeper",
        "False-positive sources": "ID", "Size or life-stage selectivity": "eggs",
        "Spatial footprint": "along-track", "Temporal resolution": "cruise",
        "Typical data latency": "year", "Public availability": "ERDDAP",
        "Questions supported (of the nine)": "eggs only", "Questions not supported": "adults",
        "FishAI holdings": "erdCalCOFIcufes 202204 ~418 rows", "sources": "global-file-inventory.csv"}),
    o(**{"Observation method": "Light traps / settlement collectors", "What is recorded": "recruits",
        "Unit of observation": "trap-night", "Effort measure": "nights",
        "Explicit zeros available?": "if recorded", "Repeated visits?": "yes",
        "Detection modifiers": "light, current", "False-negative sources": "not attracted",
        "False-positive sources": "rare", "Size or life-stage selectivity": "settlement-stage",
        "Spatial footprint": "site", "Temporal resolution": "nights",
        "Typical data latency": "program", "Public availability": "some LTER",
        "Questions supported (of the nine)": "recruitment pulse", "Questions not supported": "adult 2",
        "FishAI holdings": "none", "sources": "S62"}),
    o(**{"Observation method": "Structured citizen science (complete checklists)", "What is recorded": "seen/not seen + effort",
        "Unit of observation": "checklist", "Effort measure": "time/distance/area",
        "Explicit zeros available?": "yes if complete", "Repeated visits?": "yes",
        "Detection modifiers": "skill, vis, protocol adherence", "False-negative sources": "incomplete lists pretending complete",
        "False-positive sources": "mis-ID", "Size or life-stage selectivity": "conspicuous",
        "Spatial footprint": "user path", "Temporal resolution": "visit",
        "Typical data latency": "hours-days", "Public availability": "if FishAI builds it",
        "Questions supported (of the nine)": "2-like if protocol matches; 7 validation", "Questions not supported": "4",
        "FishAI holdings": "none yet; recommended crowd path", "sources": "S78; S80"}),
    o(**{"Observation method": "Unstructured citizen science (iNat/GBIF/OBIS)", "What is recorded": "presence pins",
        "Unit of observation": "occurrence", "Effort measure": "none",
        "Explicit zeros available?": "no", "Repeated visits?": "no design",
        "Detection modifiers": "popularity, access", "False-negative sources": "everywhere unsampled",
        "False-positive sources": "mis-ID, coordinate error", "Size or life-stage selectivity": "photogenic",
        "Spatial footprint": "point (often generalized)", "Temporal resolution": "irregular",
        "Typical data latency": "days", "Public availability": "yes",
        "Questions supported (of the nine)": "presence-only relative 1", "Questions not supported": "2-9",
        "FishAI holdings": "OBIS Keys 672; GBIF STE PART request", "sources": "S67; S68"}),
    o(**{"Observation method": "Angler catch apps", "What is recorded": "catches, sometimes spots",
        "Unit of observation": "report", "Effort measure": "usually missing",
        "Explicit zeros available?": "no", "Repeated visits?": "users",
        "Detection modifiers": "targeting, sharing incentives", "False-negative sources": "unreported zeros",
        "False-positive sources": "boast/mis-ID", "Size or life-stage selectivity": "legal/kept",
        "Spatial footprint": "often hidden or coarse", "Temporal resolution": "trip",
        "Typical data latency": "hours", "Public availability": "vendor",
        "Questions supported (of the nine)": "none scientific without effort", "Questions not supported": "all nine as ecology",
        "FishAI holdings": "none; do not adopt hotspots", "sources": "SAFETY_AND_NON_TARGETING_BOUNDARIES.md"}),
]
wcsv("OBSERVATION_METHOD_MATRIX.csv", OCOLS, obs)
print("bias+obs done")
