#!/usr/bin/env python3
"""40-row commercial matrix from NOTES_D + SOURCES_D. Research-only. No fishing advice."""
import csv
from pathlib import Path

ROOT = Path("/Users/wijeratne/dev/fishai/research/predicting-fish-distributions")
COLS = [
    "Tool",
    "Category",
    "Vendor or operator",
    "Inputs used",
    "Direct vs inferred",
    "Real output",
    "Claimed spatial resolution",
    "Claimed temporal resolution",
    "Uncertainty handling",
    "Performance evidence (independent | vendor_only | none_found)",
    "Evidence detail",
    "Marketing claims not independently validated",
    "Scientifically useful components",
    "Components FishAI must not adopt",
    "Status checked (date and whether product still exists)",
    "sources",
]


def r(**kw):
    row = {c: kw[c] for c in COLS}
    return row


rows = [
    r(
        Tool="IHO ENC / ECDIS charts",
        Category="navigational charts",
        **{"Vendor or operator": "national hydrographic offices (SOLAS)"},
        **{"Inputs used": "official hydrographic surveys; CATZOC quality zones (P700–P706; P871; P872)"},
        **{"Direct vs inferred": "direct depths and hazards for navigation; not fish"},
        **{"Real output": "carriage-compliant electronic navigational chart"},
        **{"Claimed spatial resolution": "survey-order dependent (S-44)"},
        **{"Claimed temporal resolution": "notice-to-mariners updates"},
        **{"Uncertainty handling": "CATZOC; unofficial crowd bathy cannot enter ENC (P702; P703)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "IHO S-66/S-57/S-44 specifications; charts are navigation products"},
        **{"Marketing claims not independently validated": "n/a as a hydrographic standard"},
        **{"Scientifically useful components": "named quality of depth; official vs unofficial layer split"},
        **{"Components FishAI must not adopt": "treating a chart as a fish map"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 standards in force"},
        sources="P700;P701;P702;P703;P704;P705;P706;P871;P872",
    ),
    r(
        Tool="GEBCO gridded bathymetry",
        Category="bathymetric chart",
        **{"Vendor or operator": "GEBCO"},
        **{"Inputs used": "compiled soundings and satellite altimetry grids"},
        **{"Direct vs inferred": "inferred seafloor in many cells; not a navigational ENC"},
        **{"Real output": "public-domain depth grid; terms of use: not for navigation (P709)"},
        **{"Claimed spatial resolution": "global grid (product-dependent)"},
        **{"Claimed temporal resolution": "periodic releases"},
        **{"Uncertainty handling": "compilation metadata; not a detection probability"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "public bathymetry product; terms forbid navigation use"},
        **{"Marketing claims not independently validated": "n/a"},
        **{"Scientifically useful components": "habitat-depth covariate candidate once joined to surveys"},
        **{"Components FishAI must not adopt": "fine wreck-scale public targeting layers"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 GEBCO public"},
        sources="P709",
    ),
    r(
        Tool="Garmin ActiveCaptain",
        Category="navigational software",
        **{"Vendor or operator": "Garmin"},
        **{"Inputs used": "charts, GPS, community POIs, weather; optional Quickdraw share (P710; P713)"},
        **{"Direct vs inferred": "nav direct; community fishing intel inferred by users"},
        **{"Real output": "plotter/app navigation and community layers"},
        **{"Claimed spatial resolution": "chart and community coverage"},
        **{"Claimed temporal resolution": "community continuous; weather delayed"},
        **{"Uncertainty handling": "none ecological"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "no ecological skill vs surveys; navigation tool"},
        **{"Marketing claims not independently validated": "community fishing intelligence"},
        **{"Scientifically useful components": "issue-time stamps on weather/SST overlays if shown"},
        **{"Components FishAI must not adopt": "community bite layers"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 public product exists"},
        sources="P710;P713",
    ),
    r(
        Tool="Garmin Quickdraw Contours",
        Category="bathymetric chart",
        **{"Vendor or operator": "Garmin"},
        **{"Inputs used": "user sonar depth + GPS + card (P736; P737; P873)"},
        **{"Direct vs inferred": "direct depths along tracks; interpolated contours"},
        **{"Real output": "on-device 1-foot contours; optional community share"},
        **{"Claimed spatial resolution": "1-foot contours claimed"},
        **{"Claimed temporal resolution": "as recorded"},
        **{"Uncertainty handling": "coverage follows users; not probabilistic"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "depth measurement along the boat track; not fish"},
        **{"Marketing claims not independently validated": "fishing maps from contours"},
        **{"Scientifically useful components": "crowd bathymetry with quality flags"},
        **{"Components FishAI must not adopt": "contour-as-fish marketing"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 product page live; not on all models (P873)"},
        sources="P736;P737;P873",
    ),
    r(
        Tool="Garmin Navionics+ / SonarChart",
        Category="bathymetric chart",
        **{"Vendor or operator": "Garmin (Navionics acquired; P716)"},
        **{"Inputs used": "official charts plus crowd sonar logs (P711; P712; P714; P715; P727)"},
        **{"Direct vs inferred": "direct depths; interpolated HD bathymetry"},
        **{"Real output": "licensed bathymetry; claimed 0.5 m HD; ~1 week sonar-log ingest"},
        **{"Claimed spatial resolution": "0.5 m HD claimed (P712; P727)"},
        **{"Claimed temporal resolution": "15–30 day official integration claimed; sonar ~1 week"},
        **{"Uncertainty handling": "quality varies; unofficial CSB not ENC (P702)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "sonar bathymetry is depth not fish; IHO CSB cannot enter ENC"},
        **{"Marketing claims not independently validated": "fishing-contour marketing"},
        **{"Scientifically useful components": "bathy covariate with quality flags; data/raw/habitat is empty today"},
        **{"Components FishAI must not adopt": "fishing-spot overlays; wreck-scale public layers"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 product line exists"},
        sources="P711;P712;P714;P715;P716;P727;P702",
    ),
    r(
        Tool="C-MAP Genesis",
        Category="bathymetric chart",
        **{"Vendor or operator": "C-MAP / Brunswick-Navico (P874)"},
        **{"Inputs used": "crowd sonar; .GSD depth-only vs .SL* with vegetation (P738–P740)"},
        **{"Direct vs inferred": "direct depths; vegetation/hardness inferred by algorithm"},
        **{"Real output": "social and private contour maps"},
        **{"Claimed spatial resolution": "1-foot contours claimed"},
        **{"Claimed temporal resolution": "user uploads"},
        **{"Uncertainty handling": "unspecified"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "depth not fish; vegetation claims are algorithm output"},
        **{"Marketing claims not independently validated": "fishing maps"},
        **{"Scientifically useful components": "bathy hypothesis; split depth-only files from vegetation files"},
        **{"Components FishAI must not adopt": "target contours as fish"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 social map still sold"},
        sources="P738;P739;P740;P874",
    ),
    r(
        Tool="C-MAP Genesis Live",
        Category="bathymetric chart",
        **{"Vendor or operator": "C-MAP / Lowrance (P741; P742)"},
        **{"Inputs used": "on-device sonar; Live .GSD depth and GPS only"},
        **{"Direct vs inferred": "direct depths"},
        **{"Real output": "live contours on the plotter; optional upload"},
        **{"Claimed spatial resolution": "plotter-scale contours"},
        **{"Claimed temporal resolution": "real-time on device"},
        **{"Uncertainty handling": "Live file lacks vegetation/hardness (P742)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "launched Sept 2018; depth along track"},
        **{"Marketing claims not independently validated": "instant fishing map"},
        **{"Scientifically useful components": "on-device bathy is still depth"},
        **{"Components FishAI must not adopt": "live contour as occurrence"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 documented; upload path exists"},
        sources="P741;P742",
    ),
    r(
        Tool="BioBase EcoSound",
        Category="bathymetric chart / habitat mapping",
        **{"Vendor or operator": "BioBase (shared backend with Genesis; P745; P746)"},
        **{"Inputs used": "Lowrance-class 200 kHz sonar; WAAS GPS"},
        **{"Direct vs inferred": "depth direct; vegetation and hardness inferred"},
        **{"Real output": "automated depth, vegetation, hardness maps"},
        **{"Claimed spatial resolution": "track interpolation"},
        **{"Claimed temporal resolution": "survey day"},
        **{"Uncertainty handling": "paper reports accuracy/precision vs independent measures"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "Helminen and Linnansaari 2019 (P743): independent river test for depth and vegetation, not fish"},
        **{"Marketing claims not independently validated": "fish abundance from EcoSound"},
        **{"Scientifically useful components": "independent check that consumer sonar can map depth/veg with error bars"},
        **{"Components FishAI must not adopt": "sonar-as-fish; public vegetation as a bite layer"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 BioBase pages live"},
        sources="P743;P744;P745;P746",
    ),
    r(
        Tool="TIMEZERO TZ Professional",
        Category="navigational software",
        **{"Vendor or operator": "TIMEZERO (MaxSea product name retired 2016; company continues; P718; P721; P723)"},
        **{"Inputs used": "charts, radar, AIS, PBG, SST/chl overlays, sounder module (P719; P720; P726)"},
        **{"Direct vs inferred": "nav and depths direct; ocean overlays inferred as habitat by users"},
        **{"Real output": "plotter software including a fishing workspace"},
        **{"Claimed spatial resolution": "chart + overlay"},
        **{"Claimed temporal resolution": "nav real-time; SST delayed"},
        **{"Uncertainty handling": "none ecological"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "no locked ecological test vs RVC; MaxSea brand-only after 2016"},
        **{"Marketing claims not independently validated": "ocean overlays as fish"},
        **{"Scientifically useful components": "issue-time discipline if overlay timestamps are shown"},
        **{"Components FishAI must not adopt": "fishing workspace; AIS fishing-mode colours as biomass (P722)"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 TIMEZERO live; MaxSea name retired"},
        sources="P718;P719;P720;P721;P722;P723;P724;P725;P726",
    ),
    r(
        Tool="TIMEZERO AIS fishing mode",
        Category="vessel intelligence",
        **{"Vendor or operator": "TIMEZERO / Furuno Norge notes (P722)"},
        **{"Inputs used": "AIS kinematics (speed bands)"},
        **{"Direct vs inferred": "vessels direct; fishing inferred from speed"},
        **{"Real output": "coloured AIS targets in a fishing workspace"},
        **{"Claimed spatial resolution": "AIS position"},
        **{"Claimed temporal resolution": "real-time AIS"},
        **{"Uncertainty handling": "none ecological"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "speed-banding is kinematics not biomass; GFW papers are the independent AIS literature"},
        **{"Marketing claims not independently validated": "AIS colours as fish/fishing success"},
        **{"Scientifically useful components": "none for FishAI ecology"},
        **{"Components FishAI must not adopt": "AIS-as-fish; public targeting of boats"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 described in TZ Professional v5 notes"},
        sources="P722;P815",
    ),
    r(
        Tool="Furuno DFF3D",
        Category="onboard sonar",
        **{"Vendor or operator": "Furuno"},
        **{"Inputs used": "165 kHz multibeam; claimed 300 m down / 200 m sidebar (P728–P731; P875)"},
        **{"Direct vs inferred": "direct backscatter; fish inferred by operator/AI modes"},
        **{"Real output": "water-column and 3D fish-finding display; PBG cells with TZ"},
        **{"Claimed spatial resolution": "under-keel / sidebar beams (41 beams / 8 RX noted P875)"},
        **{"Claimed temporal resolution": "real-time"},
        **{"Uncertainty handling": "operator interpretation"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "backscatter is not species without TS and a survey design (P747)"},
        **{"Marketing claims not independently validated": "3D fish-finding; Accu-Fish-class ID if advertised"},
        **{"Scientifically useful components": "none for a public FishAI layer"},
        **{"Components FishAI must not adopt": "real-time targeting display"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 Furuno USA product page live"},
        sources="P728;P729;P730;P731;P747;P875",
    ),
    r(
        Tool="Furuno WASSP F3",
        Category="onboard sonar",
        **{"Vendor or operator": "Furuno"},
        **{"Inputs used": "224 beams; 120°; 160 or 80 kHz; mapping licences (P730)"},
        **{"Direct vs inferred": "direct multibeam; seafloor mapping inferred products"},
        **{"Real output": "professional multibeam mapping"},
        **{"Claimed spatial resolution": "multibeam footprint"},
        **{"Claimed temporal resolution": "real-time underway"},
        **{"Uncertainty handling": "survey-grade claims are vendor"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "mapping sonar is not a species detection model"},
        **{"Marketing claims not independently validated": "fish-finding as ecology"},
        **{"Scientifically useful components": "possible bathy source under partnership; not public"},
        **{"Components FishAI must not adopt": "public WASSP fish images"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 Furuno product page live"},
        sources="P730",
    ),
    r(
        Tool="Simrad StructureScan / Active Imaging",
        Category="onboard sonar",
        **{"Vendor or operator": "Navico/Simrad"},
        **{"Inputs used": "side/down/forward sonar (P732–P735)"},
        **{"Direct vs inferred": "direct backscatter; structure and fish inferred by operator"},
        **{"Real output": "recreational imaging sonar"},
        **{"Claimed spatial resolution": "up to 180 m each side claimed (P733); ForwardScan 4–5× depth (P735)"},
        **{"Claimed temporal resolution": "real-time"},
        **{"Uncertainty handling": "operator"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "ForwardScan is a navigation aid (P735); imaging is not species ID"},
        **{"Marketing claims not independently validated": "AI fish ID / Accu-Fish-class claims need independent tests"},
        **{"Scientifically useful components": "none for FishAI public product"},
        **{"Components FishAI must not adopt": "real-time targeting; forward-scan as occurrence"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 Simrad pages live"},
        sources="P732;P733;P734;P735",
    ),
    r(
        Tool="Fishbrain catch map",
        Category="crowd-sourced catch-report",
        **{"Vendor or operator": "Fishbrain"},
        **{"Inputs used": "user catches, photos, some location; Garmin/C-MAP charts (P748–P752)"},
        **{"Direct vs inferred": "direct catch reports; inferred hotspots"},
        **{"Real output": "social catch map; Pro exact pins vs 1-mile radius"},
        **{"Claimed spatial resolution": "point to site"},
        **{"Claimed temporal resolution": "near real-time user posts"},
        **{"Uncertainty handling": "none scientific; coverage bias noted in support (P750)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "Helms et al. 2024 abstract (P753): cabezon ID 95.3%; RecFIN size trends not reproduced — not an ecological Brier. Gundelund 2021 (P754) and NOAA SPO-253 (P755): app data miss zeros and avidity"},
        **{"Marketing claims not independently validated": "better fishing via app data; spot predictions"},
        **{"Scientifically useful components": "none without complete effort and zeros (P757; P891)"},
        **{"Components FishAI must not adopt": "catch pins, hotspots, where-to-fish"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 public product exists (not logged-in audit)"},
        sources="P748;P749;P750;P752;P753;P754;P755;P756;P757;P891",
    ),
    r(
        Tool="Fishbrain BiteGuide",
        Category="crowd-sourced catch-report / fishing forecast",
        **{"Vendor or operator": "Fishbrain"},
        **{"Inputs used": "user logs plus proprietary BiteScore/BiteTime/Best Baits (P751)"},
        **{"Direct vs inferred": "inferred activity score; not occurrence"},
        **{"Real output": "BiteScore activity layer"},
        **{"Claimed spatial resolution": "spot / map layer"},
        **{"Claimed temporal resolution": "forecast-style product copy"},
        **{"Uncertainty handling": "none scientific"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "support text: activity score is not occurrence (P751); no locked test vs surveys"},
        **{"Marketing claims not independently validated": "BiteGuide/spot AI"},
        **{"Scientifically useful components": "none"},
        **{"Components FishAI must not adopt": "BiteScores as detection probability"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 support article live"},
        sources="P751;P749",
    ),
    r(
        Tool="SatFish",
        Category="satellite ocean-condition / fishing forecast",
        **{"Vendor or operator": "SatFish"},
        **{"Inputs used": "IR SST, chlorophyll, altimetry-class layers (P758–P762; P894)"},
        **{"Direct vs inferred": "env direct; fish inferred (bite-zone language)"},
        **{"Real output": "maps of ocean conditions marketed to anglers"},
        **{"Claimed spatial resolution": "km-class satellite"},
        **{"Claimed temporal resolution": "4–8 h SST if clear; composites daily (P759; P760)"},
        **{"Uncertainty handling": "cloud masking; typically no ecological uncertainty"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "no FishAI-verified Brier vs surveys; composites without a window are not nowcasts"},
        **{"Marketing claims not independently validated": "where fish will be; bite zones"},
        **{"Scientifically useful components": "SST/chl/fronts as covariate hypotheses; issue and valid time"},
        **{"Components FishAI must not adopt": "fishing forecast branding"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 class exists; page not logged-in"},
        sources="P758;P759;P760;P761;P762;P894",
    ),
    r(
        Tool="Terrafin SST-View",
        Category="satellite ocean-condition",
        **{"Vendor or operator": "Terrafin"},
        **{"Inputs used": "NOAA/European SST and chlorophyll (P763–P765)"},
        **{"Direct vs inferred": "env direct; fish inferred by users"},
        **{"Real output": "temp/color charts since 1998; quality stars; last 20 images"},
        **{"Claimed spatial resolution": "km"},
        **{"Claimed temporal resolution": "chlorophyll ~1/day; NASA lag ~18 h claimed (P764)"},
        **{"Uncertainty handling": "quality stars; optical limits on chlorophyll (P765)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "charts of SST/chl; no locked ecological skill vs RVC"},
        **{"Marketing claims not independently validated": "bite prediction"},
        **{"Scientifically useful components": "SST/chl visualization; lag is an issue-time lesson"},
        **{"Components FishAI must not adopt": "bite maps"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 terrafin.com/sstview live"},
        sources="P763;P764;P765",
    ),
    r(
        Tool="Hilton Realtime-Navigator",
        Category="satellite ocean-condition",
        **{"Vendor or operator": "Hilton's Fishing Charts LLC"},
        **{"Inputs used": "SST 6–12/day claimed; chlorophyll composites (P766–P769)"},
        **{"Direct vs inferred": "env direct; overlapping favourable areas inferred by the user (P768)"},
        **{"Real output": "regional fishing charts; SAT2NAV offline nav"},
        **{"Claimed spatial resolution": "km; 34–36 regions claimed"},
        **{"Claimed temporal resolution": "daily-class SST"},
        **{"Uncertainty handling": "user interpretation; no model score"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "product teaches angler inference not a Brier; competitor page still describes it as live (P876)"},
        **{"Marketing claims not independently validated": "fishing charts as occurrence"},
        **{"Scientifically useful components": "SST as a covariate hypothesis"},
        **{"Components FishAI must not adopt": "hotspots; overlapping favourable areas as detections"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 realtime-navigator.com live"},
        sources="P766;P767;P768;P769;P876",
    ),
    r(
        Tool="FishTrack",
        Category="satellite ocean-condition / fishing forecast",
        **{"Vendor or operator": "FishTrack"},
        **{"Inputs used": "cloud-free SST, chlorophyll, currents, weather (P770–P774)"},
        **{"Direct vs inferred": "env direct; bullseye lat/lon/depth/temp inferred as bite"},
        **{"Real output": "charts and app; Premium subscription"},
        **{"Claimed spatial resolution": "chart + bullseye"},
        **{"Claimed temporal resolution": "several times/day claimed"},
        **{"Uncertainty handling": "cloud-free composites hide missing data unless a window is stated"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "no independent locked ecological test found this pass"},
        **{"Marketing claims not independently validated": "bite-zone / fishing-forecast copy"},
        **{"Scientifically useful components": "named ocean layers as hypotheses"},
        **{"Components FishAI must not adopt": "bullseye as a fish pin"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 fishtrack.com and app stores live"},
        sources="P770;P771;P772;P773;P774",
    ),
    r(
        Tool="ROFFS",
        Category="dynamic habitat / fishing forecast",
        **{"Vendor or operator": "Roffer's Ocean Fishing Forecasting Service"},
        **{"Inputs used": "IR, colour, altimeter, analyst interpretation (P784–P788; P896)"},
        **{"Direct vs inferred": "env + expert inference"},
        **{"Real output": "custom fishing analyses; pinpoint locations described (P785)"},
        **{"Claimed spatial resolution": "regional charts / analyst dots"},
        **{"Claimed temporal resolution": "short-term client analyses"},
        **{"Uncertainty handling": "not a published Brier"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "NASA Spinoff (P786) and customer quotes are not locked tests; commercial success ≠ ecological validation"},
        **{"Marketing claims not independently validated": "find fish; pinpoint X-marks"},
        **{"Scientifically useful components": "front/current analysis as hypotheses"},
        **{"Components FishAI must not adopt": "paid hotspot forecasts; analyst X-marks as occurrence"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 roffs.com live"},
        sources="P784;P785;P786;P787;P788;P896",
    ),
    r(
        Tool="Forecast Ocean Plus (Japan)",
        Category="satellite ocean-condition / ocean forecast",
        **{"Vendor or operator": "Forecast Ocean Plus, Inc. (JAMSTEC venture; Tokyo; P775–P777)"},
        **{"Inputs used": "JCOPE 1/12° NW Pacific; FGO ~10 km claimed"},
        **{"Direct vs inferred": "ocean state direct; fishing use inferred by clients"},
        **{"Real output": "ocean forecast and consulting including fishing industries"},
        **{"Claimed spatial resolution": "1/12° / ~10 km claimed"},
        **{"Claimed temporal resolution": "ocean-forecast cadence (vendor)"},
        **{"Uncertainty handling": "vendor"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "ocean state is not species occurrence; no FishAI locked test"},
        **{"Marketing claims not independently validated": "fishing-industry skill claims if any"},
        **{"Scientifically useful components": "issue-time ocean forecast archive lesson"},
        **{"Components FishAI must not adopt": "ocean forecast as a fish map"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 forecastocean.com live"},
        sources="P775;P776;P777",
    ),
    r(
        Tool="OceanPlus Ltd (UK)",
        Category="navigational software",
        **{"Vendor or operator": "OceanPlus Ltd"},
        **{"Inputs used": "weather routing (P778)"},
        **{"Direct vs inferred": "weather/route direct; not fish"},
        **{"Real output": "UK weather routing; not a satellite fishing map"},
        **{"Claimed spatial resolution": "route scale"},
        **{"Claimed temporal resolution": "voyage"},
        **{"Uncertainty handling": "n/a ecological"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "name collision only; do not conflate with Forecast Ocean Plus"},
        **{"Marketing claims not independently validated": "n/a as a fishing product (it is not one)"},
        **{"Scientifically useful components": "none for FishAI ecology"},
        **{"Components FishAI must not adopt": "merging distinct OceanPlus entities"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 LinkedIn listing; not a fishing product"},
        sources="P778",
    ),
    r(
        Tool="CLS CATSAT",
        Category="tuna-fleet decision support",
        **{"Vendor or operator": "CLS / Thalos"},
        **{"Inputs used": "SST, SLA, plankton, zooplankton, micronekton, AIS (P779–P783)"},
        **{"Direct vs inferred": "env + fleet tools; micronekton inferred from models"},
        **{"Real output": "onboard ocean products; >1200 vessels claimed; longliner hook-depth tools"},
        **{"Claimed spatial resolution": "km-class products"},
        **{"Claimed temporal resolution": "daily-class"},
        **{"Uncertainty handling": "vendor"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "fleet tools are not survey likelihoods; fishing-intelligence claims untested vs RVC"},
        **{"Marketing claims not independently validated": "smart fishing intelligence; micronekton as tuna"},
        **{"Scientifically useful components": "ocean layers as hypotheses"},
        **{"Components FishAI must not adopt": "fleet targeting; micronekton maps as fish pins"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 catsat.com and CLS pages live"},
        sources="P779;P780;P781;P782;P783",
    ),
    r(
        Tool="INCOIS Potential Fishing Zone advisories",
        Category="dynamic habitat / fishing forecast",
        **{"Vendor or operator": "INCOIS (Government of India)"},
        **{"Inputs used": "satellite SST and chlorophyll fronts (P789–P793; P794; P795)"},
        **{"Direct vs inferred": "env direct; catchability inferred"},
        **{"Real output": "PFZ advisories operational since ~1999 class"},
        **{"Claimed spatial resolution": "coastal advisory polygons"},
        **{"Claimed temporal resolution": "short-term advisories"},
        **{"Uncertainty handling": "operational product; not a detection probability"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "paired-boat or landing-centre CPUE tests show higher catch rates in SST–chl features (P789–P791) — catchability, not occurrence or abundance"},
        **{"Marketing claims not independently validated": "equating CPUE-on-a-front with ecological abundance"},
        **{"Scientifically useful components": "front detection as a catchability hypothesis; do not import as Q1/Q2"},
        **{"Components FishAI must not adopt": "PFZ-style public go-fish polygons for reef fish"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 literature and program docs checked; not a FishAI layer"},
        sources="P789;P790;P791;P792;P793;P794;P795",
    ),
    r(
        Tool="Satlink ISD+ FAD buoy",
        Category="onboard/remote sonar",
        **{"Vendor or operator": "Satlink"},
        **{"Inputs used": "dual echosounder on drifting FADs (P796; P801)"},
        **{"Direct vs inferred": "backscatter direct; species mix inferred"},
        **{"Real output": "satellite buoy acoustic messages; manufacturer biomass indices"},
        **{"Claimed spatial resolution": "FAD-scale"},
        **{"Claimed temporal resolution": "hours"},
        **{"Uncertainty handling": "research papers discuss TS mix; manufacturer tonnes ≠ Sv (P809)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "Lopez et al. 2016 (P802): manufacturer biomass r=0.50; behaviour model r=0.90 on fitted sets. RFMO BAI papers after reprocessing (P803–P808). Not the vendor app."},
        **{"Marketing claims not independently validated": "exact tonnes / species composition on the buoy"},
        **{"Scientifically useful components": "relative standardised acoustic index research (Q3 internal)"},
        **{"Components FishAI must not adopt": "public FAD-level targeting; vendor tonnage as truth"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 Satlink product page live"},
        sources="P796;P801;P802;P803;P809;P887",
    ),
    r(
        Tool="Marine Instruments M3i+ FAD buoy",
        Category="onboard/remote sonar",
        **{"Vendor or operator": "Marine Instruments"},
        **{"Inputs used": "50/200 kHz; 150 m; 3 m layers; 6 m blind zone (P797–P799)"},
        **{"Direct vs inferred": "backscatter direct; AI tuna tonnage inferred (WEAK)"},
        **{"Real output": "echo-sounder satellite buoy"},
        **{"Claimed spatial resolution": "FAD-scale"},
        **{"Claimed temporal resolution": "sounding cadence"},
        **{"Uncertainty handling": "blind zone 6 m; brand mixing caution in IATTC (P808; P809)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "scientific literature uses buoy acoustics as a relative-abundance research index after converting vendor scales to Sv; AI tonnage is vendor"},
        **{"Marketing claims not independently validated": "AI tuna tonnage (P799)"},
        **{"Scientifically useful components": "sensor-based index research example"},
        **{"Components FishAI must not adopt": "public FAD maps; mixing brands as one biomass unit"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 product pages live"},
        sources="P797;P798;P799;P808;P809",
    ),
    r(
        Tool="Zunibal Tuna8 Xtreme",
        Category="onboard/remote sonar",
        **{"Vendor or operator": "Zunibal"},
        **{"Inputs used": "FAD echosounder; 4320 soundings/day claimed; 120 m scale (P800)"},
        **{"Direct vs inferred": "backscatter direct; biomass inferred"},
        **{"Real output": "tuna FAD buoy"},
        **{"Claimed spatial resolution": "120 m scale claimed"},
        **{"Claimed temporal resolution": "4320 soundings/day claimed"},
        **{"Uncertainty handling": "vendor"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "appears in WCPFC acoustic datasets with Satlink (P810; P811); weak catch link in Escalle et al.; species unresolved"},
        **{"Marketing claims not independently validated": "vendor biomass"},
        **{"Scientifically useful components": "restricted industry archives for Q3 research only"},
        **{"Components FishAI must not adopt": "public FAD positions"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 zunibal.com product page live"},
        sources="P800;P810;P811",
    ),
    r(
        Tool="Kato FAD echosounder buoys",
        Category="onboard/remote sonar",
        **{"Vendor or operator": "Kato (historical in WCPFC data)"},
        **{"Inputs used": "FAD acoustics in 2016–2018 WCPFC datasets (P811)"},
        **{"Direct vs inferred": "backscatter if present"},
        **{"Real output": "unknown current consumer product"},
        **{"Claimed spatial resolution": "FAD-scale in historical data"},
        **{"Claimed temporal resolution": "historical transmissions"},
        **{"Uncertainty handling": "n/a"},
        **{"Performance evidence (independent | vendor_only | none_found)": "none_found"},
        **{"Evidence detail": "P811 lists Kato in 2016–2018 data; no current consumer page confirmed 2026-09-27"},
        **{"Marketing claims not independently validated": "n/a (page not found)"},
        **{"Scientifically useful components": "none currently"},
        **{"Components FishAI must not adopt": "assuming a live Kato public product"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 no live consumer page confirmed"},
        sources="P811",
    ),
    r(
        Tool="Global Fishing Watch apparent fishing",
        Category="vessel intelligence",
        **{"Vendor or operator": "Global Fishing Watch / research partners"},
        **{"Inputs used": "AIS speed/course; VIIRS lights; SAR (P815–P826)"},
        **{"Direct vs inferred": "vessels direct; fishing inferred"},
        **{"Real output": "apparent fishing effort maps; 0.01° daily / 0.1° monthly products"},
        **{"Claimed spatial resolution": "0.01° / 0.1° grids (P824)"},
        **{"Claimed temporal resolution": "hours–days; v4 pipeline 26 Feb 2026 (P825)"},
        **{"Uncertainty handling": "papers discuss classification error; public AIS is incomplete"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "Kroodsma et al. 2018 (P815): AIS fishing footprint. Paolo et al. 2024 Nature (P819): 72–76% of industrial fishing vessels not in public AIS. This is vessel effort not fish. CC BY-NC (P823; P898)."},
        **{"Marketing claims not independently validated": "n/a as a science org (do not treat effort as fish)"},
        **{"Scientifically useful components": "effort as a sampling-bias covariate if citizen checklists exist; IUU research"},
        **{"Components FishAI must not adopt": "AIS as fish location; public targeting of boats; scraping against CC BY-NC"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 GFW public maps exist; Belize VMS hours paused in v4 note"},
        sources="P815;P819;P820;P822;P823;P824;P825;P898",
    ),
    r(
        Tool="Vantor Maritime Sentry",
        Category="vessel intelligence",
        **{"Vendor or operator": "Vantor (Maxar Intelligence rebranded Oct 2025; P829)"},
        **{"Inputs used": "EO, SAR, AIS; dark-vessel detection (P827–P831)"},
        **{"Direct vs inferred": "vessels direct"},
        **{"Real output": "maritime domain awareness; NIWC Pacific contract (Sep 2026); SeaVision API"},
        **{"Claimed spatial resolution": "meters-class imagery"},
        **{"Claimed temporal resolution": "tasked"},
        **{"Uncertainty handling": "vendor"},
        **{"Performance evidence (independent | vendor_only | none_found)": "vendor_only"},
        **{"Evidence detail": "ships not fish; Maxar SENTRY launch 2024 then Vantor rebrand"},
        **{"Marketing claims not independently validated": "maritime domain awareness as fish finding"},
        **{"Scientifically useful components": "none for ecology"},
        **{"Components FishAI must not adopt": "vessel hunting"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 vantor.com Sentry live"},
        sources="P827;P828;P829;P830;P831",
    ),
    r(
        Tool="EcoCast",
        Category="scientific conservation DOM",
        **{"Vendor or operator": "NOAA / partners (Welch, Hazen, Scales)"},
        **{"Inputs used": "observer+tag models + daily satellite ocean (P832–P841)"},
        **{"Direct vs inferred": "inferred habitat/bycatch risk and fishing suitability"},
        **{"Real output": "daily bycatch-risk vs fishing-suitability surface; not a legal fishing chart (P834)"},
        **{"Claimed spatial resolution": "regional grid"},
        **{"Claimed temporal resolution": "daily"},
        **{"Uncertainty handling": "paper discusses missing data and sensor-switch sensitivity (P837; P839)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "Hazen et al. 2018 (P832): dynamic closures 2–10× smaller than static leatherback closure. Welch 2019: Acquisition–Prediction–Dissemination–Automation. Seary 2024: DGN fishery sunset ~2027 so operational context is changing (P840; P870)."},
        **{"Marketing claims not independently validated": "n/a (do not invert into a bite map)"},
        **{"Scientifically useful components": "one question, validation, daily ocean, issue time, coarsened public grids"},
        **{"Components FishAI must not adopt": "turning EcoCast into a public bite map"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 CoastWatch EcoCast still served"},
        sources="P832;P833;P834;P837;P839;P840;S74",
    ),
    r(
        Tool="TurtleWatch",
        Category="scientific conservation DOM",
        **{"Vendor or operator": "NOAA"},
        **{"Inputs used": "SST isotherms; fishery interactions; tracks (P842–P846)"},
        **{"Direct vs inferred": "habitat inferred"},
        **{"Real output": "avoidance guidance; 63.5–65.5 F band; leatherback expansion (P845)"},
        **{"Claimed spatial resolution": "regional SST band"},
        **{"Claimed temporal resolution": "operational product class"},
        **{"Uncertainty handling": "habitat not location"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "Howell et al. 2008 product literature. Siders et al. (P846): band still associated with loggerhead interactions, but fishers did not avoid it (skill ≠ behaviour change)."},
        **{"Marketing claims not independently validated": "n/a"},
        **{"Scientifically useful components": "thermal habitat + conservation framing; later independent check"},
        **{"Components FishAI must not adopt": "inverting into go here for turtles; assuming a map changes behaviour"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 NOAA map resource still posted"},
        sources="P842;P843;P844;P845;P846;S77",
    ),
    r(
        Tool="WhaleWatch",
        Category="scientific conservation DOM",
        **{"Vendor or operator": "NOAA/partners"},
        **{"Inputs used": "tag-derived habitat + ocean (P847; P848)"},
        **{"Direct vs inferred": "habitat/density inferred"},
        **{"Real output": "blue whale habitat likelihood, density, error (Hazen et al. 2017)"},
        **{"Claimed spatial resolution": "monthly 25 km in the 2017 paper"},
        **{"Claimed temporal resolution": "monthly (original)"},
        **{"Uncertainty handling": "occurrence, density, and error published together"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "Hazen et al. 2017 (P847): density 0–3.5 per 625 km²; uncertainty on the map"},
        **{"Marketing claims not independently validated": "n/a"},
        **{"Scientifically useful components": "uncertainty belongs on the map; tagged animals only"},
        **{"Components FishAI must not adopt": "fine whale pins; copying SST onto reef fish"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 NOAA West Coast page live"},
        sources="P847;P848;S76",
    ),
    r(
        Tool="WhaleWatch 2.0",
        Category="scientific conservation DOM",
        **{"Vendor or operator": "NOAA CoastWatch"},
        **{"Inputs used": "ensemble habitat models (Abrahms et al. 2019 lineage; P849; P850)"},
        **{"Direct vs inferred": "habitat inferred"},
        **{"Real output": "successor daily habitat model"},
        **{"Claimed spatial resolution": "CoastWatch product (daily 10 km noted on related pages)"},
        **{"Claimed temporal resolution": "daily class"},
        **{"Uncertainty handling": "ensemble (P850)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "dynamic ensemble models paper (P850); this pass did not extract a new AUC. Still habitat, not untagged-fish pins."},
        **{"Marketing claims not independently validated": "n/a"},
        **{"Scientifically useful components": "ensemble + daily habitat with a stated question"},
        **{"Components FishAI must not adopt": "daily whale habitat as a fish nowcast template without labels"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 CoastWatch WhaleWatch 2.0 about page live"},
        sources="P849;P850",
    ),
    r(
        Tool="CSIRO/AFMA southern bluefin tuna habitat",
        Category="scientific conservation / seasonal habitat forecast",
        **{"Vendor or operator": "CSIRO / AFMA / CAWCR"},
        **{"Inputs used": "tag habitat + ocean analyses/POAMA (P854–P859; P878)"},
        **{"Direct vs inferred": "habitat inferred; management zoning"},
        **{"Real output": "near-real-time spatial management and seasonal habitat forecasts (Great Australian Bight)"},
        **{"Claimed spatial resolution": "regional habitat types / boundary"},
        **{"Claimed temporal resolution": "nowcast plus seasonal (months)"},
        **{"Uncertainty handling": "skill reported by season/lead in papers"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "Hobday and Hartmann 2006 nowcast origin; Hobday et al. 2010 AFMA zoning since 2003; Hobday et al. 2011 POAMA skill 3–4 months for habitat boundary; Eveson et al. 2015 GAB skill ~2 months in season. Habitat/management, not reef-fish RVC."},
        **{"Marketing claims not independently validated": "copying SBT habitat onto Keys damselfish"},
        **{"Scientifically useful components": "issue time; skill by lead versus ocean analyses; named management question"},
        **{"Components FishAI must not adopt": "issuing a fish forecast without archived leads and contemporaneous labels"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 CSIRO GAB forecast page still linked"},
        sources="P854;P855;P856;P857;P858;P859;P878",
    ),
    r(
        Tool="NASA/NOAA/EUMETSAT ocean-colour and SST archives",
        Category="satellite ocean-condition",
        **{"Vendor or operator": "NASA OB.DAAC; NOAA STAR; EUMETSAT Sentinel-3"},
        **{"Inputs used": "IR SST, ocean colour (P894; P895; P896)"},
        **{"Direct vs inferred": "geophysical fields direct"},
        **{"Real output": "public satellite archives used by ROFFS/Terrafin/SatFish"},
        **{"Claimed spatial resolution": "sensor-dependent km-class"},
        **{"Claimed temporal resolution": "orbit / daily composites"},
        **{"Uncertainty handling": "cloud-limited IR SST (P895)"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "public geophysical inputs; vendors add interpretation. Not a fish product."},
        **{"Marketing claims not independently validated": "n/a on the archive itself"},
        **{"Scientifically useful components": "issue and valid time; cloud flags; do not treat SST as bottom temperature"},
        **{"Components FishAI must not adopt": "SST/chl as a fish map; shallow-reef chlorophyll as a default covariate"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 archives public"},
        sources="P894;P895;P896",
    ),
    r(
        Tool="CMEMS/AVISO altimetry",
        Category="satellite ocean-condition",
        **{"Vendor or operator": "CMEMS / AVISO"},
        **{"Inputs used": "SSH, geostrophic currents (P897)"},
        **{"Direct vs inferred": "sea-surface height direct; currents inferred"},
        **{"Real output": "altimetry products used in Hilton/CATSAT/TZ overlays"},
        **{"Claimed spatial resolution": "altimetry grid"},
        **{"Claimed temporal resolution": "delayed/near-real-time product streams"},
        **{"Uncertainty handling": "product manuals"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "geophysical currents are not fish location"},
        **{"Marketing claims not independently validated": "n/a on the archive"},
        **{"Scientifically useful components": "front/current hypotheses after a locked later-year test"},
        **{"Components FishAI must not adopt": "altimetry overlays as bite zones"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 AVISO public"},
        sources="P897",
    ),
    r(
        Tool="eBird complete checklists (analogue, not a fishing tool)",
        Category="crowd-sourced catch-report (negative analogue)",
        **{"Vendor or operator": "Cornell Lab of Ornithology"},
        **{"Inputs used": "complete lists with effort (P757; S80)"},
        **{"Direct vs inferred": "detections and non-detections at stated effort"},
        **{"Real output": "relative abundance at reference effort — birds, not fish"},
        **{"Claimed spatial resolution": "checklist / 3 km product grids in Status and Trends"},
        **{"Claimed temporal resolution": "weekly products"},
        **{"Uncertainty handling": "effort-standardized models"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "included as the contrast: complete checklists supply zeros; Fishbrain-class pins do not"},
        **{"Marketing claims not independently validated": "n/a"},
        **{"Scientifically useful components": "effort + complete list requirement for any future crowd path"},
        **{"Components FishAI must not adopt": "importing eBird volume claims as a marine fact"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 analogue only; not a fishing product"},
        sources="P757;S80",
    ),
    r(
        Tool="Angler-app literature (Gundelund/Venturelli class)",
        Category="crowd-sourced catch-report",
        **{"Vendor or operator": "multiple apps (evidence class, not one vendor)"},
        **{"Inputs used": "self-selected catch reports"},
        **{"Direct vs inferred": "presence of a reported catch; zeros usually missing"},
        **{"Real output": "non-probabilistic catch streams"},
        **{"Claimed spatial resolution": "user-chosen"},
        **{"Claimed temporal resolution": "user-chosen"},
        **{"Uncertainty handling": "rarely modelled"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "Gundelund 2021; Venturelli 2017; Jiorle 2016; Tate 2025; NOAA SPO-253: missing zeros, avidity, sampling-frame issues (P754–P756; P890–P892)"},
        **{"Marketing claims not independently validated": "apps as stock-assessment replacements"},
        **{"Scientifically useful components": "why complete checklists are the only crowd path"},
        **{"Components FishAI must not adopt": "pins as training labels"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 literature class"},
        sources="P754;P755;P756;P890;P891;P892",
    ),
    r(
        Tool="Maxwell/Dunn dynamic ocean management reviews",
        Category="scientific conservation DOM",
        **{"Vendor or operator": "research literature (not a vendor app)"},
        **{"Inputs used": "simulations and case studies of dynamic vs static closures (P851–P853)"},
        **{"Direct vs inferred": "management-area inference"},
        **{"Real output": "efficiency arguments for dynamic closures"},
        **{"Claimed spatial resolution": "case-specific"},
        **{"Claimed temporal resolution": "dynamic"},
        **{"Uncertainty handling": "paper-specific"},
        **{"Performance evidence (independent | vendor_only | none_found)": "independent"},
        **{"Evidence detail": "Maxwell 2015: 34–82% less area than static in simulation. Dunn 2016: static closures 4–5× catch displacement. These are management-area results, not fish pins."},
        **{"Marketing claims not independently validated": "using DOM papers as a license to publish harvest maps"},
        **{"Scientifically useful components": "smaller time-varying closures vs static boxes; still need observations"},
        **{"Components FishAI must not adopt": "dynamic harvest advice"},
        **{"Status checked (date and whether product still exists)": "2026-09-27 papers"},
        sources="P851;P852;P853",
    ),
]

assert len(rows) == 40, len(rows)
names = [x["Tool"] for x in rows]
assert len(names) == len(set(names)), [n for n in names if names.count(n) > 1]

out = ROOT / "COMMERCIAL_TOOL_CAPABILITY_MATRIX.csv"
with out.open("w", newline="", encoding="utf-8") as f:
    w = csv.DictWriter(f, fieldnames=COLS)
    w.writeheader()
    w.writerows(rows)
print("wrote", out, "rows", len(rows))
